### PR TITLE
Issue with grouped checkboxes in firefox

### PR DESCRIPTION
**Pull request by jamesbrobb**
Can someone comfirm this please. I'm using:

OSX 10.7.5
Firefox 33.1.1

1) Go to either

http://djangular.aws.awesto.com/form_validation/

or

http://djangular.aws.awesto.com/combined_validation/

2) Scroll to 'notify me' and select 'postcard' -- i get the 'required' error message

3) deselect 'postcard' -- i get the valid tick

4) select more than one checkbox in the group and the valid tick appears

5) deselect all and the tick stays until you reselect one

Also, once you've force submitted the form to ajax (in any browser) with no checkboxes selected, the valid tick does not appear once any checkboxes are selected.

### CODE REVIEW

**Comment by jrief** [comment]
Sorry, for for the delay.

**Comment by jrief** [comment]
BTW, PR #144 will soon be merged and we will release version 0.8.0.
Could you please add a small summary of this PR to ``docs/changelog.rst``.

**Comment by jrief** [comment]
Today, in another project I used the form validation for multiple fields.
Something, which caused a major problem in my project, was your code modification of this PR.
You added ``ng-change="changed()"`` as an attribute to input fields. This manipulation of the DOM, in AngularJS is an anti-pattern.
I will remove this and return to a pure ``link`` function.

**Comment by jamesbrobb** [comment]
Can you be a bit more specific please. What exactly was the problem that it caused?

**Comment by jrief** [comment]
I don't like, that a directive adds other ng-... directives to the DOM and I strongly believe that this use case was not intended by the Angular team.

Just revered your PR from December. However, I now fixed the FF issue myself in a much cleaner and simpler way. Please recheck with your installation.

**Comment by jamesbrobb** [comment]
If you look at my commits you'll see that the first quick fix i came up with for this issue, was to simply wrap the `change` event handlers call to `validate` in a $timeout. Which then safely calls `scope.$apply`. Which is essentially what you're doing. So i understand why the issue is occurring.

The problem i have with the quick fix of `scope.$apply`, is that *it* feels like a hack. Its just a brute force solution that fails to understand why this issue only occurs in FF and not in chrome, safari or IE.

That aside, i can understand why you might consider my solution using `ng-change` to be a 'hack', as you believe it accidentally fixes the issue. But i can assure you it was a very much intentional and considered approach. 

Within angular an inputs current state is represented by its `ngModel`. But your logic mixes and matches angular model/controller state and DOM state (checkbox.checked) to determine the current state of the form. Which is not the correct way to handle this scenario. You should be monitoring the checkbox's `ngModel` for change (thus the use of the `ng-change` directive) and then use those values to determine the current state of the form. The `ngModel` should be the single source of state.

Regardless of how `ng-change` is added to the input (i'm currently looking at an alternative solution that uses `ngModel.$viewlisteners` instead - **but am also wondering if this attribute couldn't just be added in the python widget?**), i strongly believe that what i've outlined and initially implemented, is the correct way to deal with this scenario.

**Comment by jamesbrobb** [comment]
One other thing. The reversion has reintroduced an issue. If you submit the form via ajax with no inputs selected for 'Notify by', the rejected error message is correctly displayed.

If you then select a checkbox, the error message disappears, but the valid tick never re-appears, as the parent `ngForm` needs to have its 'rejected' error and `$message` cleared.

So at line 155, below

```formCtrl.$setValidity('required', valid);```

you need to add
```
formCtrl.$setValidity('rejected', true);
formCtrl.$message = '';
```

**Comment by jrief** [comment]
> The problem i have with the quick fix of scope.$apply, is that it feels like a hack. Its just a brute force solution that fails to understand why this issue only occurs in FF, but not in chrome, safari or IE.

Since I use the jQuery ``.on('change')`` event handler, which is outside the control of AngularJS, ``scope.$apply()`` IMHO is the appropriate solution.

The big problem I had with your solution was, that I added a ``ng-change`` directive to one of my Radio fields. It took me a while to find out that it is overridden by the ``validate-multiple-fields`` directive.

``ngModel.$viewChangeListeners`` seems to be an interesting solution. Will dig into the docs for that.

Thanks for reporting the seconds issue. What's that 'rejected' property? This is not part of the form errors, so I did not understand its purpose.

**Comment by jamesbrobb** [comment]
'rejected' is part of your `djangoForm`factory logic. It's how you deal with server errors.

**Comment by jamesbrobb** [comment]
@jrief Just to clarify why 'rejected' needs to be removed from the form in this instance.

When 'rejected' errors are applied in the  `djangoForm` factory `setErrors` method, this block of logic is run, that loops the errors and uses the key to apply each error to a field.

```
angular.forEach(errors, function(errors, key) {
	var field;
	if (errors.length > 0) {
		if (key === NON_FIELD_ERRORS) {
			form.$message = errors[0];
			form.$setPristine();
		} else if (form.hasOwnProperty(key)) {
			field = form[key];
			field.$message = errors[0];
			field.$setValidity('rejected', false);
			field.$setPristine();
			if (isField(field)) {
				resetFieldValidity(field);
			} else {
				// this field is a composite of input elements
				angular.forEach(field, function(subField, subKey) {
					//this can occur in 1.3 due to new 'pending' prop being undefined
					if (subField && isField(subField)) {
						resetFieldValidity(subField);
					}
				});
			}
		}
	}
});
```
Using the example form as an example, a 'required' error is returned for the `notifyme` field if an ajax submission is made and nothing is supplied. But `notifyme` is not a field, it's an `ngFormController` that manages the selection of the 4 'notifyme' checkboxes.

So in this block of logic from the above code (your original code, not a later addition) , the `field` having everything set on it is actually the `notifyme` `ngFormController`.

```
field = form[key];
field.$message = errors[0];
field.$setValidity('rejected', false);
field.$setPristine();
```
This is the same `formController` that's returned by `require` in the `validateMultipleFields` directive. Which is why those properties need to be cleared in that directive to reset the state of the `ngFormController`. If `$setValidity('rejected', true)` is not called, the 'rejected' error is never removed from the `notifyme` `ngFormController` (which is why the valid tick is never displayed) and it's `$invalid` state is always 'true'. So its parent `formController` is also never valid.

You can see this on the demo form by following these steps:

http://djangular.aws.awesto.com/combined_validation/

1) Select 'Force Submission via Ajax'

- 'Notify Me' displays its 'rejected error' as `my_form.notifyme.$message` and `my_form.notifyme.$pristine` are both true

2) Select any of the 'Notify Me' checkboxes

- the error message disappears but the valid tick does not show as `my_form.notifyme` is still invalid due to the existing 'rejected' error. But as `my_form.notifyme.$pristine` is now false (due to the selection) the error message is no longer visible.

3) Fill in the rest of the form so that every field is valid

- even though the form now appears to be valid, the 'Submit via Post' and 'Submit via Ajax' buttons never become enabled.

4)  Select 'Force Submission via Ajax'

- the form is successfully submitted, showing that the data was actually valid

------------------------------------------------------------------------------------------------------------------------------------------

> Although TBH i'm not 100% clear on what there exact purpose is, as the values that are cleared in the listener function, don't appear to ever actually be set anywhere?

Returning to this point, i'm not sure what purpose it serves also adding the `$viewChangeListeners` (through the `resetFieldValidity` function) to each `subField` of the `ngFormController`. As the values that are cleared in that listener function are *never* actually set on each `subField`?

```
// this field is a composite of input elements
angular.forEach(field, function(subField, subKey) {
	if (subField && isField(subField)) {
		resetFieldValidity(subField);
	}
});
```

**Comment by jrief** [comment]
@jamesbrobb 
Can you please send me your email address.

**Comment by jamesbrobb** [comment]
I've added it to my profile

**Comment by jamesbrobb** [comment]
#160 offers an alternative fix for everything mentioned in this issue

**Pull request merged**
