### PR TITLE
ng-model-options debounce prevents default value from being displayed

### PR DESCRIPTION
**Pull request by jamesbrobb**
In the `ngModel` directive `restoreInputField`method you need to call `modelCtrl.$commitViewValue()`after `modelCtrl.$setViewValue()`to ensure that the default value is displayed

### CODE REVIEW

**Comment by jamesbrobb** [comment]
@jrief You can ignore everything here except for the final commit.

This is my preferred fix for this issue, as it simply sets the default values directly onto the scope model, which `ngModel` then uses to populate the fields, thus making it version agnostic. Going forward, if any new features are added to the angular 1.x branch that may affect this feature, no modification will be necessary for it to work.

For an alternate fix that's closer to your original, but which tests for 1.3 features, please see issue #152.

**Comment by adrienbrunet** [comment]
Hi @jamesbrobb I'm trying to go through old issues and PR to clean this repo a bit. Do you know if this PR is still needed? Can you point me a failing behavior right that this PR fixes? You said there is an alternative solution for that problem? I'm eager to merge #152 as well 'cause I'm facing this issue right now...

**Comment by jamesbrobb** [comment]
Hi @adrienbrunet , i'm afraid i'm not as it's been a while since i submitted this PR (and the rest) and i've not used django-angular since, so i have no idea what's been changed. It's worth looking at #160, as i'd found quite a few issues with the way the JS has been written and give a fairly extensive explanation of the changes i'd made.

**Comment by adrienbrunet** [comment]
@jrief I'm closing this one. If we need to merge something, it should be from PR #152 
@jamesbrobb contributions are really good, the problem is explained and the solution is quite clear as well. Code is well structured. It kust takes A LOT of time to read it through, understand the problem, the solution and ensure the way it's done is one of the best we can come up with. Sorry for the delay..

**Pull request closed without merging**
