### PR TITLE
request.environ['QUERY_STRING'] in UTF-8

### PR DESCRIPTION
**Pull request by metteludwig**
Instead of unicode, which breaks things. Solves #213.

### CODE REVIEW

**Comment by adrienbrunet** [comment]
Hi, thanks for your contribution. Due to python3, the merge is not possible. (see travis)

**Comment by metteludwig** [comment]
Aw, shucks. Should've known the Py3-tests would fail. New commit now. Thanks for quick feedback.

**Comment by adrienbrunet** [comment]
Looks good to me.

**Comment by adrienbrunet** [comment]
I'm not confortable enough with that issue to merge it myself. Not sure exactly what urlencode do in the first place. Would you have the time to provide a failing test of this behavior? (which obviously should pass with your changes?) @jrief can you have a quick look?

Anyway, thanks a lot for what you're doing !

**Comment by metteludwig** [comment]
I currently don't have time to create the test, although the straight forward approach would be comparing `request.GET['param']` between `/api/?param=åäö` and `/angular/reverse/?djng_url_name=api&param=åäö`. 

Thanks for providing this package. It helps a bunch.

**Comment by adrienbrunet** [comment]
@jrief what do you think about it? Merge?

**Comment by jrief** [comment]
@adrienbrunet Yes, I'm very favorable to this.
It would be nice, if a unit test could catch future problems on this.
Specially, if you write code which must be compatible between Py3-Py2 it is very easy to overlook some edge cases.
@metteludwig would it be possible to add such a test?

**Comment by jkosir** [comment]
Looks good to me and I'd also ask for a simple test case to demonstrate it.
Could we release 0.8 after merging this?

On Friday, December 18, 2015, Jacob Rief <notifications@github.com> wrote:

> @adrienbrunet <https://github.com/adrienbrunet> Yes, I'm very favorable
> to this.
> It would be nice, if a unit test could catch future problems on this.
> Specially, if you write code which must be compatible between Py3-Py2 it
> is very easy to overlook some edge cases.
> @metteludwig <https://github.com/metteludwig> would it be possible to add
> such a test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrief/django-angular/pull/214#issuecomment-165763112>.
>


-- 
Lep pozdrav,
Jakob Košir

**Comment by adrienbrunet** [comment]
See PR #216

**Pull request closed without merging**
