### PR TITLE
Remove DJANGULAR_VALIDATION_MAPPING_MODULE from docs

### PR DESCRIPTION
**Pull request by jsSenanga**
This setting was removed in c545fb5672df35261fe90b312e5ff09b85efe535
No documentation is better then incorrect documentation...?

### CODE REVIEW

**Comment by jsSenanga** [comment]
Would still be nice to have documentation about "Adding form validation to customized fields".
But for now, I think it's better to remove this paragraph. It avoids sending people on a wild goose chase.

**Comment by adrienbrunet** [comment]
Ok, thanks. I'll create the issue as a reminder for that doc. Would you be able to write it?

**Comment by jsSenanga** [comment]
Can't promise anything yet. Still just evaluating to usage of django-angular for my project. But if I do and figure out how, I'll try and write this :)

**Comment by jrief** [comment]
@jsSenanga  Sorry, I oversaw this.
Anyway, the additional functionality required for fields is now handled by some classes located in ``fields_mixins``. New docs should mention this file.

**Pull request merged**
