### PR TITLE
Jamesbrobb django messages

### PR DESCRIPTION
**Pull request by adrienbrunet**
This is entirely @jamesbrobb work. I just rebased his work on our current master to get rid of the merge conflicts.

Now that we're able to merge, it could be a nice addition. What do you think @jrief and @jkosir ?

Note: I've just read quickly the code, haven't tested it yet.

### CODE REVIEW

**Comment by adrienbrunet** [comment]
Original description:

This adds support to seamlessly pass django messages to an angular app via ajax.

You can either use the Middleware or a view decorator to add the current messages to the HttpResponse of an ajax request (when the response Content-Type is application/json).

Then the messages are extracted from the response data by a HttpInterceptor, which also returns the remaining data to it's original/expected format.

There's a demo page that needs more detail and also docs.

**Comment by jrief** [comment]
Cool stuff! I was thinking about this feature myself, but had no time to implement it.
Many thanks to @jamesbrobb

**Comment by adrienbrunet** [comment]
Erf, I need to make it work and then we can all have a closer look at it.

**Comment by adrienbrunet** [comment]
@jrief tests pass now. =) Haven't tried it though, I don't really have the need for it right now. Would be great if you can have a look and merge it.

**Comment by adrienbrunet** [comment]
I'm going to add compatibility for django1.10 and we're good to go. Or at least, review it :smiling_imp:

**Comment by jrief** [comment]
a few day ago I started to merge that PR locally. However, I had to adopt a lot of code and then I was distracted with other work.

btw. I had a look at a possible implementation of the client part, http://jsfiddle.net/roopehakulinen/uxeg4nze/
how do you like that?

**Comment by adrienbrunet** [comment]
That's neat! Currently adding django1.10 support. We'll see then what we can do. :)

**Comment by adrienbrunet** [comment]
:+1:

**Pull request closed without merging**
