### PR TITLE
Change the widget css class using a dictionary similar to field_css_classes

### PR DESCRIPTION
**Pull request by jshridha**
This is a merge request to allow changing the css class for widgets using a dictionary key similar to field_css_classes. I need this to be able to add a datepicker class to certain form fields.

### CODE REVIEW

**Comment by adrienbrunet** [comment]
I'm always saying it to new contributors: thanks a lot for your pull request.
Right now, I can't merge it as is. Could you provide documentation for this feature? What about a test and/or an example? If you don't have time for that, I'll do it but it won't be really soon. Again, thanks! :+1:

**Comment by jrief** [comment]
Thanks @jshridha for this PR.
You you please elaborate what kind of problem you want to resolve. Maybe there is an easier solution.
Also, please add or modify a unit test to check your code against possible future regressions.

**Comment by jshridha** [comment]
@jrief I'm trying to add a class only to specific widgets. Currently the widget_css_classes field applies a class to every widget, but I only want to apply a class to certain widgets similar to how field_css_classes work.

If there is an easier solution, I'm all ears :)

I'll work on adding in a unit test and some documentation if you feel the feature is useful. I ended up no longer needing this for my project, but others might find this useful as well.

**Comment by adrienbrunet** [comment]
This is not such a bad idea. It does more or less the same thing that the field_css_classes magic does and could be usefull. BUT, why should we care adding this feature? You could add in your form definition:

    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.fields['my_field'].widget.attrs['class'] = 'my_new_class'


Or you could define a custom widget.
I don't feel confortable adding new features which are not really the django encouraged way of doing things. What do you both think ?

**Comment by jshridha** [comment]
I completely agree. If there is a more Django centric way of doing it, then
that is the right way of doing it.

I tried adjusting the widget attribute of the method class within the form,
but those classes were getting overwritten by djangular's methods within
the bootstrap mixin. I didn't try overriding the init method, I'll try that
and if that works it's definitely the preferred solution.

**Comment by adrienbrunet** [comment]
Let us know if the override of `__init__` works. Then, we can close this. (I'm doing a Christmas :christmas_tree:  cleaning hehe)

**Comment by jshridha** [comment]
I'm currently in the car driving to Christmas, but found a chance to try it
out :). It still gets overwritten. The class attr isn't set by the end of
the init method, so I just need to find the right method in the mixin to
hook into.

**Comment by adrienbrunet** [comment]
Hahaha you rock! :guitar: If you find it, please let us know! But maybe you have better things to do today, enjoy ! :cake: :christmas_tree: :santa:

**Comment by jshridha** [comment]
I was just on the edge of finding the bug and ran out of battery on my
laptop. There's something that happens very early on, even before looking
at widget_css_classes that ignores or deletes the class key in the widget's
attrs dict. It may be coming in from the ngboundfield mixin, but I'll have
to search for it later.

**Comment by adrienbrunet** [comment]
You' re awesome, merry christmas :santa: Try to work plugged in next time haha

**Comment by jshridha** [comment]
I was able to find the bug that was causing the class attr to be overwritten and I updated the pull request. Hopefully it passes the travisci checks!

**Comment by adrienbrunet** [comment]
:fireworks: Yay, that works. Great job =)

**Comment by adrienbrunet** [comment]
Hey, I reverted the PR. In fact, is attrs['class'] always defined? If it is defined as an empty string, maybe it would be better to `' '.join([our, classes])` and if attrs['class'] is not defined, It wont work. I merged it too quickly. There are no tests for that so we need to be very carefull.

**Comment by jshridha** [comment]
Before I updated the pull request, I checked to see if there were any cases where the attrs['class'] was not defined. I couldn't get any, but I decided to update the pull request to check anyway just in case. It is now updated!

**Comment by adrienbrunet** [comment]
Unfortunately, I don't know how to do it without creating a new one. :sob:

**Pull request merged**
