### PR TITLE
Modifications on NgModelFormMixin to support ng-options.

### PR DESCRIPTION
**Pull request by thnee**
Hi,
Thanks for a very helpful library.
I hope you will get a chance to review these changes.
Very open to any feedback, I'm using this on a daily basis.
This is my first pull request ever..

### CODE REVIEW

**Comment by sgbirch** [comment]
This patch would have solved a problem we are having, we need to repopulate dropdowns from the controller using ng-options.  Whet would I have to do to have the patch considered again?

**Comment by jrief** [comment]
@sgbirch how about adding ``ng-options`` to ``attrs`` and overriding the field's widget?
``ng-options`` in a django-angular context is somehow the opposite of the primary intention of that library: keeping the business logic inside Django.

**Comment by adrienbrunet** [comment]
Indeed that works for me. In your form `__init__`,  for example you can add:

`self.fields['my_field'].widget.attrs['ng-options'] = 'el.pk as el.readable_attr for el in list_el'`

It does mix angular elements ("list_el") inside django though.

**Comment by sgbirch** [comment]
I agree.  What we are trying to do is restrict the number of items in a dropdown based on selections made elsewhere on a form.  For example, if a county is selected in one dropdown the "county" dropdown will only contain counties in the selected country.

It is actually making an ajax call back to the database to get the new drop down info but I can't see how to change the list of <SELECT> items without using ng-options.

**Comment by adrienbrunet** [comment]
Once you're adding ng-options to your `__init__`, if you look at my example, "list_el" refers to an angular list of element. It can be the result of an ajax call. I'm not sure to get your problem

**Comment by sgbirch** [comment]
I can't thank you enough.  That has solved the problem perfectly, I wrote my reply before understanding your solution.  Thank you!!!!!!

**Comment by adrienbrunet** [comment]
:smile:

**Comment by jrief** [comment]
@adrienbrunet yes, since it can help other to not waste time searching for tricky solution.
Modifying field's widgets is is a common problem even outside of **django-angular**; there are many Stack-Overflow Q&Aa about this.

**Comment by sgbirch** [comment]
Sure, I can do that. Where is the best place to have a stab at it?  FAQ or a section in the manual?

**Comment by jrief** [comment]
Indeed, a FAQ section is missing. @adrienbrunet @jkosir what do you think?

**Comment by adrienbrunet** [comment]
Indeed, a FAQ section could be really helpful. But I feel that this particular issue is really common, we may add a subsection to: 'Integrate a django form with an AngularJS model.' to state how to use ng-options, ng-init, etc.

There is a doc called `tutorial-forms.rst` which explained how to use `field_css_class` to add `ng-show`/`ng-hide`, we may also use that to gather all form customization at one place. But this file does not appear in the docs, it is not included in the index.rst. Is there a reason? Cheers

**Comment by jrief** [comment]
Hmm, I simply forgot to add this to the index.rst.

I now added a section **Adding Additional Attributes** to tutorial-forms. @sgbirch please write a few lines explaining how you solved your problem, so that other users can benefit from it. If you don't want to create a PR, just add that text to this issue, then I will merge it. Thanks, Jacob

**Comment by sgbirch** [comment]
OK .. thanks

Steve

**Comment by sgbirch** [comment]
I haven't added documentation yet because I am having a tough time making this work.  The following line in the Form constructor is being used:

self.fields['county'].widget.attrs['ng-options'] = 'e.id as e.name for e in ctrl.counties'

The generated html looks correct:

 `<select id="id_ctrl.county" name="ctrl.county" ng-change="ctrl.changedItem()" ng-model="ctrl.county"     ng-options="e.id as e.name for e in ctrl.counties">`
`<option value="">---------</option>`
`<option value="96">Non Applicable</option>`
`<option value="1">Allen</option>`

But when the form is posted django sent the following in request.POST['ctrl.county']

`request.POST[ctrl.county] = number:5`

Instead of just 1.  Any idea what may be causing this behaviour?

**Comment by sgbirch** [comment]
@adrienbrunet I am having great trouble debugging this, can you help?  I have changed the attribute field per your suggestion:

`self.fields['county'].widget.attrs['ng-options'] = 'e.id as e.name for e in ctrl.counties'`

This works very well.  The ajax call in the controller to determine what should be placed in ctrl.counties all works perfectly.   The only problem is when the form is submitted back to django the selected value has a 'number:' prefix.

For example, instead of getting '7' in request.POST(ctrl.county) I am getting 'number:7'

Any ideas what I have done wrong?

**Comment by adrienbrunet** [comment]
You mean `request.POST.get('county') == 1` ?
Using:

    self.fields['myfield'].widget.attrs['ng-options'] = 'e.pk as e.name for e in _list_in_angular'

you should have in your POST data 'myfield': e.pk

I have no idea where your "number:1" comes from.
Have you done anything with the serialization? I guess `id` == `pk`.

**Comment by sgbirch** [comment]
I changed the code to request.POST.get() and also changed id to pk but still the pesky "number:" is returned.

I am not doing anything with serialization.

One thing you said before was that the field's widget needed to be overridden.  I didn't do that, just added the following to the Form's initializer:

```python
def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    self.fields['county'].widget.attrs['ng-options'] = 'e.pk as e.name for e in ctrl.counties'
```

Could that be the problem?  Is there anything in Angular that might add the "number:"?

So close ..... yet, so far!

**Comment by sgbirch** [comment]
I still haven't tracked down the "number:" serialization. I am pretty sure it is being added by Angular but I am not familiar enough to track it down.  I added no code to my form for handling the submit, just mixed in your classes.  So, the form code looks like this:

```python
class EventForm(NgModelFormMixin, NgModelForm):
 
     def add_prefix(self, field_name):
         return "ctrl." + field_name
 
     def __init__(self, *args, **kwargs):
         super(EventForm, self).__init__(*args, **kwargs)
         #self.fields['roads'].widget = widgets.RelatedFieldWidgetWrapper(
         #        formfield.widget, Road.objects.all(), self.admin_site)
 
         #
         # Set up the ng-options field used by Angular to populate dropdowns
         #
 
         self.fields['county'].widget.attrs['ng-options'] = 'e.pk as e.name for e in ctrl.counties'
         self.fields['district'].widget.attrs['ng-options'] = 'e.pk as e.name for e in ctrl.districts'
         self.fields['sub_district'].widget.attrs['ng-options'] = 'e.pk as e.name for e in ctrl.sub_districts'
 ```

Does that look correct?

**Pull request closed without merging**
