### PR TITLE
Use django regex to validate email addresses

### PR DESCRIPTION
**Pull request by omarkhan**
#### Background

Django's email validation is much stricter than Angular's. In particular, Angular allows any domain, including those without a tld:

    foo@bar

This can cause the form to validate client-side but fail to validate on the server.

#### Proposal

Use the same regex as Django to validate email addresses.

#### Implementation

Django uses [a combination of 3 regexes and some custom code](https://github.com/django/django/blob/2cd2d188516475ddf256e6267cd82c495fb5c430/django/core/validators.py#L166) to validate email addresses. Rather than try to replicate that logic exactly, I have added a `get_email_regex` method to the `EmailFieldMixin` class that concatenates the user and domain regexes (including whitelisted domains) into a single javascript-compatible regex. This regex is then added to the input as the `email-pattern` attribute. If the `validate-email` directive is included on the input element, this pattern will be used to validate email addresses instead of the Angular default email validation. For example:

```python
class MyForm(NgFormValidationMixin, NgForm):
    email = forms.EmailField(widget=forms.widgets.EmailInput(attrs={
        'validate-email': True
    }))
```

#### Caveats

- Internationalized domain names are not supported
- IP addresses not supported
- The Django regex checks that email addresses do not end with a hyphen `-` character using a negative lookbehind. Javascript regexes do not support lookbehinds, so this is stripped.

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for this PR, this annoyed me a little bit myself.
Just for curiosity, why do you extract the Regex from the email field instead of hard coding it?

**Comment by omarkhan** [comment]
Just to keep it DRY.

**Comment by jrief** [comment]
your PR has been published in
https://pypi.python.org/pypi/django-angular/0.8.2

**Comment by omarkhan** [comment]
Great, thanks for the quick response on this issue!

**Pull request merged**
