### PR TITLE
Bootstrap4

### PR DESCRIPTION
**Pull request by adrienbrunet**
Needs some more heavy testing before merge. I seldom make use of bootstrap4.

I've added a note in the docs to announce support for bootstrap4.
All bootstrap3 mixins now have an equivalent for bootstrap4.

Bootstrap common code has been refactored in a bootstrap module inside djng/styling

A page to ease bootstrap4 testing has been added in examples. (Same layout than other subscribe forms)

### CODE REVIEW

**Comment by elcone** [comment]
thank's @adrienbrunet I'll test it and leave you my comments \m/

**Comment by adrienbrunet** [comment]
@elcone Did you have the chance to test it? All good? Ready for merge?

**Comment by adrienbrunet** [comment]
@elcone ? :smile:

**Comment by adrienbrunet** [comment]
@jrief should we merge it now or nobody seems interested enough and we'll wait a bit more?

**Comment by jrief** [comment]
With the next release of **django-angular** and Django-1.11 there is no more need to use the ``styling/bootstrap/whatever.py`` submodules, since it is enough to create an alternative template.

I'm sorry, if that pull request remains unmerged, but the new widget rendering functions are much more flexible and easier to override for alternative CSS frameworks.

**Comment by adrienbrunet** [comment]
No worries ! I'm closing this then !

**Pull request closed without merging**
