### PR TITLE
Added support for Django 1.9 (.travis.yml), removed some warnings for Django 1.10

### PR DESCRIPTION
**Pull request by viaregio**

### CODE REVIEW

**Comment by adrienbrunet** [comment]
Yep, all good for me. @jrief Should we keep maintaining django 1.5? So far, we don't have that much pain doing it but it might get harder... With this new config, we *really* should release version 0.8
:pray:

**Comment by jrief** [comment]
Support for Django-1.5 can be dropped. In my opinion we can even drop support for Django-1.6.

Personal annotation: I was able to migrate my main projects to Django-1.7 only a few month ago. That's kind of problem for me, because I can't keep up all the projects with their newest dependencies.

**Comment by adrienbrunet** [comment]
Okay, but you're not alone jacob =) We're facing the same problem and some awesome people help us to keep it up with the latest dependencies. :smile:

@viaregio : would you please remove the support for django 1.5 (at least) in your commit and I'll merge your pull request? Cheers!

**Comment by jrief** [comment]
Thanks @viaregio for proceeding to 1.9!

**Comment by adrienbrunet** [comment]
:+1:

**Comment by viaregio** [comment]
Thanks @jrief, @adrienbrunet for your work on this project.

**Pull request merged**
